// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdrapdfniyzltpzpsavn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkcmFwZGZuaXl6bHRwenBzYXZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMzQ2NjQsImV4cCI6MjA2ODcxMDY2NH0.vu4jjgfBIgccnBxPZxEoqJCSlO-iJdHqms5PCJ_VOpk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});